### ISSUE TITLE
Refined GitHub updates

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1137]
# Welcome to Refined GitHub! <img src="https://raw.githubusercontent.com/sindresorhus/refined-github/master/source/icon.png" width="32">

You can subscribe to this thread to receive updates regarding new features added to the extension. Click the `Subscribe` button in the sidebar!

## Contributing

Suggestions and pull requests are highly encouraged! Have a look at the [open issues](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+sort%3Areactions-%2B1-desc), especially [the easy ones](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+sort%3Areactions-%2B1-desc). Check out [contributing.md](https://github.com/sindresorhus/refined-github/edit/master/contributing.md) for more info!

**Comment by bfred-it** [comment]
https://github.com/sindresorhus/refined-github/issues/818

**Comment by bfred-it** [comment]
- [Automatically closes modals when they’re no longer visible](https://user-images.githubusercontent.com/1402241/37022353-531c676e-2155-11e8-96cc-80d934bb22e0.gif)
- [Shows all keyboard shortcuts in the help modal](https://user-images.githubusercontent.com/29176678/36999174-9f07d33e-20bf-11e8-83e3-b3a9908a4b5f.png)  *(<kbd>?</kbd> hotkey)*
- [Adds links to the default branch and to the latest semver release](https://user-images.githubusercontent.com/1402241/36961980-389bd2b0-2080-11e8-8bff-bb8af52e7128.png)
- [Adds `Commented` button to Issues/Pull Requests page](https://user-images.githubusercontent.com/8295888/36827126-8bfc79c4-1d37-11e8-8754-992968b082be.png)
- [Highlight closing PRs in open issues and PRs](https://user-images.githubusercontent.com/1402241/37037746-8b8eac8a-2185-11e8-94f6-4d50a9c8a152.png)
- [Show latest tag in `latest release button`](https://user-images.githubusercontent.com/1402241/36968396-f9115420-2094-11e8-8bd6-ddc1748a891d.png)

**Comment by bfred-it** [comment]
- [Open multiple issues at once in your repos.](https://user-images.githubusercontent.com/1402241/38084752-4820b0d8-3378-11e8-868c-a1582b16f915.gif)
- [Possibly-related issues are shown when creating a new issue.](https://user-images.githubusercontent.com/29176678/37566899-85953e6e-2abf-11e8-9f0e-52d18c87bbe3.gif)
- [Merged PRs show the closing commit in the header.](https://user-images.githubusercontent.com/1402241/38155415-d9175d2e-34a1-11e8-9b2a-f56a880a0d3f.png)
- [Permalinked comments are highlighted.](https://user-images.githubusercontent.com/1402241/37349492-226bd37a-2709-11e8-8087-d9686b330240.png) [Example](https://github.com/sindresorhus/refined-github/issues/1137#issuecomment-370799864) on this page.
- [Add your own custom CSS to GitHub without having to install Stylish.](https://github.com/sindresorhus/refined-github/pull/1193)
- [Inactive deployments in PR timelines are hidden.](https://github.com/sindresorhus/refined-github/issues/1144)

**Comment by sindresorhus** [comment]
- [GitHub has implemented many of Refined GitHub's features natively](https://github.com/sindresorhus/refined-github#previously-part-of-refined-github) through their [Paper Cuts initiative](https://blog.github.com/2018-08-28-announcing-paper-cuts/). 🎉
- [Refined GitHub with GitHub Enterprise now works on Firefox.](https://github.com/sindresorhus/refined-github/pull/1596)
- [404 pages are now more useful.](https://github.com/sindresorhus/refined-github/pull/1558)
- [Navigate with arrow keys through pages with navigation.](https://github.com/sindresorhus/refined-github/pull/1542)
- [User profile contribution activity automagically expand when you scroll down.](https://github.com/sindresorhus/refined-github/commit/179179d4c2d943e758582318dfa7999f9f14f535)
- [Useless comments are now hidden.](https://github.com/sindresorhus/refined-github/commit/ee9375aa16eaad9b05eb90b72f6082fbd8fe08e5)
- [You'll now see a badge on a user's profile if they follow you.](https://user-images.githubusercontent.com/3723666/45190460-03ecc380-b20c-11e8-832b-839959ee2c99.gif)
- [Forks are hidden from a user's Repositories list (but they can still be shown).](https://user-images.githubusercontent.com/1402241/45133648-fe21be80-b1c8-11e8-9052-e38cb443efa9.png)
- [Filter PRs that you haven't submitted a review for.](https://user-images.githubusercontent.com/9264728/42569205-0c32a376-8510-11e8-9406-b3ddcf6087ef.png)
- [Followers you know are shown on profile pages.](https://user-images.githubusercontent.com/2906365/42009293-b1503f62-7a57-11e8-88f5-9c2fb3651a14.png)

**Comment by sindresorhus** [comment]
- Refined GitHub was rewritten in TypeScript.
- [Add co-authors when merging PRs with multiple committers.](https://user-images.githubusercontent.com/1402241/51468821-71a42100-1da2-11e9-86aa-fc2a6a29da84.png) https://github.com/sindresorhus/refined-github/commit/e0bce6fcbe0dc21006d320bf72b974af13ba544a
- [Insert collapsible content when writing comments (via `<summary>`).](https://user-images.githubusercontent.com/1402241/53678019-0c721280-3cf4-11e9-9c24-4d11a697f67c.png) https://github.com/sindresorhus/refined-github/commit/547795cb5e204b2465e32d306d64a3eae1879747
- [Your issues and PRs are highlighted in the issue/PR list.](https://user-images.githubusercontent.com/1402241/53065281-01560000-3506-11e9-9a51-0bdf69e20b4a.png) https://github.com/sindresorhus/refined-github/commit/681bf2c20a14e0212e0724ab1b8cd67784c3fa03
- [Search for issues and PRs separately in the global search.](https://user-images.githubusercontent.com/1402241/52181103-35a09f80-2829-11e9-9c6f-57f2e08fc5b2.png) https://github.com/sindresorhus/refined-github/commit/abebd9fc7b9f07d8ea0981b0f6e196ef0c5483ca
- Star/unstar a repository by pressing <kbd>g</kbd> <kbd>s</kbd>. https://github.com/sindresorhus/refined-github/commit/9eb93b11e9a8c4bdc1ba19a91ec153fd1dc1af57
- [Bypass the "Checks" page and go directly to the Travis build when clicking the "Details" links on a PR](https://user-images.githubusercontent.com/2103975/49071220-c6596e80-f22d-11e8-8a1e-bdcd62aa6ece.png) https://github.com/sindresorhus/refined-github/commit/5c45ccb0313b813c76e6a673bd7ee2c83fb394ba
- [Exclude PR/issue filters from their list](https://user-images.githubusercontent.com/1402241/48470535-493cfb00-e824-11e8-863a-964f52b62553.png) with <kbd>alt/option</kbd>-<kbd>click</kbd>. https://github.com/sindresorhus/refined-github/commit/07b247295255d37a4f61df60a19b688d4b903a1d
- [Find a user’s most starred repositories in their profile.](https://user-images.githubusercontent.com/1402241/48474026-43e3ae80-e82c-11e8-93de-159ad4c6f283.png) https://github.com/sindresorhus/refined-github/commit/483dc65817d3104e87cb0b0b4067bbb20a10eb7d
- [The PR/issues search box expands when focused.](https://user-images.githubusercontent.com/1402241/48473156-7ab8c500-e82a-11e8-95c7-a39b0529fe1b.gif) https://github.com/sindresorhus/refined-github/commit/29faf28bb816cbecb8fb834d5461a22fd9913eda
- [Significant head and base branches are shown in the PR list.](https://user-images.githubusercontent.com/1402241/50545950-ed9ec380-0c51-11e9-803c-7ae489baf5e1.png) https://github.com/sindresorhus/refined-github/commit/f25483fa128d9dcc8e1e74fcf2d2751d604fe11f
- [GitHub has implemented even more of Refined GitHub's features natively](https://github.com/sindresorhus/refined-github#previously-part-of-refined-github) through their [Paper Cuts initiative](https://blog.github.com/2018-08-28-announcing-paper-cuts/).

**Comment by bfred-it** [comment]
- [Fix merge conflicts in a click](https://user-images.githubusercontent.com/1402241/54978791-45906080-4fdc-11e9-8fe1-45374f8ff636.png) ← https://github.com/sindresorhus/refined-github/pull/1882
 - [Follow file renames in commits lists](https://user-images.githubusercontent.com/1402241/54799957-7306a280-4c9a-11e9-86de-b9764ed93397.png) ← https://github.com/sindresorhus/refined-github/pull/1870
 - [View the source of Markdown files](https://user-images.githubusercontent.com/1402241/54814836-7bc39c80-4ccb-11e9-8996-9ecf4f6036cb.png) ← https://github.com/sindresorhus/refined-github/pull/1873
 - [Hidden comments are previewed inline](https://user-images.githubusercontent.com/1402241/52545036-6e271700-2def-11e9-8c0c-b5e0fa6f37dd.png) ← https://github.com/sindresorhus/refined-github/pull/1755
 - [Change diff style and whitespace visibility in one click](https://user-images.githubusercontent.com/1402241/54178764-d1c96080-44d1-11e9-889c-734ffd2a602d.png) ← https://github.com/sindresorhus/refined-github/pull/1799
 - [Press <kbd>esc</kbd> to deselect the current line when viewing files](https://github.com/sindresorhus/refined-github/issues/1590) ← https://github.com/sindresorhus/refined-github/pull/1878
 - [Comment boxes expand with their content and no longer show scroll bars](https://user-images.githubusercontent.com/1402241/54336211-66fd5e00-4666-11e9-9c5e-111fccab004d.gif) ← https://github.com/sindresorhus/refined-github/pull/1871
 - [Edit comments in one click](https://user-images.githubusercontent.com/1402241/54864831-92372a00-4d97-11e9-8c29-efba2dde1baa.png) ← https://github.com/sindresorhus/refined-github/pull/1880
 - [Your issues and PRs are highlighted](https://user-images.githubusercontent.com/1402241/53065281-01560000-3506-11e9-9a51-0bdf69e20b4a.png) ← https://github.com/sindresorhus/refined-github/pull/1782
 - [Insert collapsible content when writing comments (via `<details>`)](https://user-images.githubusercontent.com/1402241/53678019-0c721280-3cf4-11e9-9c24-4d11a697f67c.png) ← https://github.com/sindresorhus/refined-github/pull/1804
 - [Forks and watchers counters are hidden](https://user-images.githubusercontent.com/1402241/53681077-f3328b80-3d1e-11e9-9e29-2cb017141769.png) ← https://github.com/sindresorhus/refined-github/pull/1820
 - [Text wrapped in \`backticks\` in issue titles is highlighted](https://user-images.githubusercontent.com/170270/55060505-31179b00-50a4-11e9-99a9-c3691ba38d66.png) ← https://github.com/sindresorhus/refined-github/pull/1872
 - The `Projects` tab is hidden from repositories **and profiles** when there are no projects. https://github.com/sindresorhus/refined-github/pull/1788
 - [A warning appears when trying to create a PR from the default branch](https://user-images.githubusercontent.com/1402241/52543516-3ca94e00-2de5-11e9-9f80-ff8f9fe8bdc4.png) ← https://github.com/sindresorhus/refined-github/pull/1758
 - [Links to an issue's closing commit, not just pull request](https://user-images.githubusercontent.com/1402241/53860046-a4386f00-401a-11e9-999f-4b382b92bceb.png) ← https://github.com/sindresorhus/refined-github/pull/1832
 - [Diff signs are hidden](https://user-images.githubusercontent.com/1402241/54807718-149cec80-4cb9-11e9-869c-e265863211e3.png) ← https://github.com/sindresorhus/refined-github/pull/1866
 - [The PR/issues search box is wider](https://user-images.githubusercontent.com/1402241/55069759-bceaf080-50bf-11e9-84d0-7707de2eb9e9.png) ← https://github.com/sindresorhus/refined-github/pull/1886
 - [Tall code blocks and quotes are limited in height](https://github.com/sindresorhus/refined-github/issues/1123) ← https://github.com/sindresorhus/refined-github/pull/1146
 - [Search for issues and PRs separately in the top search](https://user-images.githubusercontent.com/1402241/52181103-35a09f80-2829-11e9-9c6f-57f2e08fc5b2.png) ← https://github.com/sindresorhus/refined-github/pull/1738
 - [Access `Commits` and `Branches` from the `More` dropdown](https://user-images.githubusercontent.com/1402241/55089736-d94f5300-50e8-11e9-9095-329ac74c1e9f.png) ← https://github.com/sindresorhus/refined-github/pull/1825

**Comment by bfred-it** [comment]
-  [See an automatic changelog for each tag or release.](https://user-images.githubusercontent.com/1402241/57081611-ad4a7180-6d27-11e9-9cb6-c54ec1ac18bb.png) ← https://github.com/sindresorhus/refined-github/pull/1998
 - [Update a PR from the base branch to ensure it build correctly before merging the PR itself (same-repo branches only).](https://user-images.githubusercontent.com/1402241/57941992-f2170080-7902-11e9-8f8a-594aad983559.png) ← https://github.com/sindresorhus/refined-github/pull/1950
- [Update the PR’s title to the merge commit title, if changed.](https://user-images.githubusercontent.com/1402241/51669708-9a712400-1ff7-11e9-913a-ac1ea1050975.png) ← https://github.com/sindresorhus/refined-github/pull/1960
- [Edit files straight from a repo’s list by clicking their icon.](https://user-images.githubusercontent.com/1402241/56370462-d51cde00-622d-11e9-8cd3-8a173bd3dc08.png) ← https://github.com/sindresorhus/refined-github/pull/1939
 - [Filter pull requests by their build status.](https://user-images.githubusercontent.com/22439276/56372372-7733ca80-621c-11e9-8b60-a0b95aa4cd4f.png) ← https://github.com/sindresorhus/refined-github/pull/1904
- [Browse a repository at the time of each comment,](https://user-images.githubusercontent.com/1402241/56450896-68076680-635b-11e9-8b24-ebd11cc4e655.png) including [each link.](https://user-images.githubusercontent.com/1402241/56450895-68076680-635b-11e9-86b4-b6c2f3745d51.png) ← https://github.com/sindresorhus/refined-github/pull/1863
- [Search or select tags from a dropdown in the `Releases` page.](https://user-images.githubusercontent.com/22439276/56373231-27ee9980-621e-11e9-9b21-601919d3dddf.png) ← https://github.com/sindresorhus/refined-github/pull/1896
- The `checks` tab in PR is removed unless you're owner ← https://github.com/sindresorhus/refined-github/pull/1929
- [View the raw version of files in PRs and commits.](https://user-images.githubusercontent.com/1402241/56484988-b99f2500-6504-11e9-9748-c944e1070cc8.png) ← https://github.com/sindresorhus/refined-github/pull/1924
 - [Hide milestone sorter UI if you don’t have permission to use it.](https://user-images.githubusercontent.com/7753001/56913933-738a2880-6ae5-11e9-9d13-1973cbbf5df0.png) ← https://github.com/sindresorhus/refined-github/pull/1980
 - [SVG files in a PR default to rich-diff view.](https://user-images.githubusercontent.com/5243867/57125552-c08a2b00-6d81-11e9-9b84-cdb535baa98e.png) ← https://github.com/sindresorhus/refined-github/pull/1932
 - [Link to file itself in the history pages](https://user-images.githubusercontent.com/22439276/57195061-b88ddf00-6f6b-11e9-8ad9-13225d09266d.png) ← https://github.com/sindresorhus/refined-github/pull/2000
 - [Empty sections in the issue/PRs sidebar are hidden or collapsed.](https://user-images.githubusercontent.com/1402241/57199809-20691780-6fb6-11e9-9672-1ad3f9e1b827.png) ← https://github.com/sindresorhus/refined-github/pull/2011

**Comment by bfred-it** [comment]
- [Open issues to the latest comment by clicking the comments icon.](https://user-images.githubusercontent.com/14323370/57962709-7019de00-78e8-11e9-8398-7e617ba7a96f.png) ←  #2028
- Wrap code inside all code blocks to match indentation.  ← #1989
- [The most useful comment in issues is highlighted.](https://user-images.githubusercontent.com/1402241/58757449-5b238880-853f-11e9-9526-e86c41a32f00.png)  ← #2108
- [Download count is shown next to release assets.](https://user-images.githubusercontent.com/14323370/58944460-e1aeb480-874f-11e9-8052-2d4dc794ecab.png) ←  #2027
- [Projects and Milestones filters are dropped if they are empty.](https://user-images.githubusercontent.com/37769974/59083449-0ef88f80-8915-11e9-8296-68af1ddcf191.png) ←  #2114
- [Cycle "popover lists" (labels, milestones, etc) when selecting them with the <kbd>↑</kbd> and <kbd>↓</kbd> keys.](https://user-images.githubusercontent.com/37769974/59158786-6fd2c400-8add-11e9-9db1-db80186fa6ea.gif) ←  #2140
- [Add upload button to the comment toolbar and remove the upload message.](https://user-images.githubusercontent.com/55841/59802383-3d994180-92e9-11e9-835d-60de67611c30.png) ←  #2157
- [Limits the length of commit fields to 72 characters](https://user-images.githubusercontent.com/37769974/59830368-1c723880-935d-11e9-9408-6deb2e516fd5.png) ←  #2115

**Comment by fregante** [comment]
July 2019

- [](# "linkify-symbolic-links") [Linkifies symbolic links files.](https://user-images.githubusercontent.com/1402241/62036664-6d0e6880-b21c-11e9-9270-4ae30cc10de2.png) ← https://github.com/sindresorhus/refined-github/pull/2277

- [](# "show-whitespace") 🔥 [Shows whitespace characters.](https://user-images.githubusercontent.com/1402241/61187598-f9118380-a6a5-11e9-985a-990a7f798805.png) ← https://github.com/sindresorhus/refined-github/pull/2073

- [](# "list-prs-for-file") [Shows PRs that touch the current file.](https://user-images.githubusercontent.com/55841/60622834-879e1f00-9de1-11e9-9a9e-bae5ec0b3728.png) ← https://github.com/sindresorhus/refined-github/pull/2197

- [](# "submit-review-as-single-comment") [Adds a button to submit a single PR comment if you mistakenly started a new review.](https://user-images.githubusercontent.com/1402241/60331761-f6394200-99c7-11e9-81c2-c671cba9602a.gif)  ← https://github.com/sindresorhus/refined-github/pull/2188

- [](# "forked-to") [Adds a shortcut to your forks next to the `Fork` button on the current repo.](https://user-images.githubusercontent.com/55841/64077281-17bbf000-cccf-11e9-9123-092063f65357.png) ← https://github.com/sindresorhus/refined-github/pull/2153

**Comment by fregante** [comment]
August 2019

- [Hide unnecessary tip on comment field](https://user-images.githubusercontent.com/19228201/63220373-9c890480-c13a-11e9-98a0-d84aec51070a.png) ← https://github.com/sindresorhus/refined-github/pull/2375

- [](# "hidden-review-comments-indicator") [Adds comment indicators when comments are hidden in PR review.](https://user-images.githubusercontent.com/1402241/63112671-011d5580-bfbb-11e9-9e19-53e11641990e.gif) ← https://github.com/sindresorhus/refined-github/pull/2320

- [](# "revert-file") [Adds button to revert all the changes to a file in a PR.](https://user-images.githubusercontent.com/1402241/62826118-73b7bb00-bbe0-11e9-9449-2dd64c469bb9.gif) ← https://github.com/sindresorhus/refined-github/pull/2182

- [](# "hide-zero-packages") [Hides the `Packages` tab in repositories if it’s empty.](https://user-images.githubusercontent.com/35382021/62426530-688ef780-b6d5-11e9-93f2-515110aed1eb.jpg) ← https://github.com/sindresorhus/refined-github/pull/2301

**Comment by fregante** [comment]
November 2019

- [](# "user-local-time") [Shows the user local time in their hovercard (based on their last commit).](https://user-images.githubusercontent.com/1402241/69863648-ef449180-12cf-11ea-8f36-7c92fc487f31.gif) ← https://github.com/sindresorhus/refined-github/pull/2549

- [](# "repo-age") [Adds the age of the repository to the statistics bar.](https://user-images.githubusercontent.com/3848317/69494069-7d2b1180-0eb7-11ea-9aa1-d4194e566340.png) ← https://github.com/sindresorhus/refined-github/pull/2560

- [](# "linkify-user-location") [Linkifies the user location in their hovercard and profile page.](https://user-images.githubusercontent.com/1402241/69076885-00d3a100-0a67-11ea-952a-690acec0826f.png) ← https://github.com/sindresorhus/refined-github/pull/2544

- [](# "linkify-labels-on-dashboard") [Makes labels clickable in the dashboard’s "Recent activity" box.](https://user-images.githubusercontent.com/1402241/69045444-6ef97300-0a29-11ea-99a3-9a622c395709.png) ← https://github.com/sindresorhus/refined-github/pull/2513

- [](# "fix-view-file-link-in-pr") [Points the "View file" in PRs to the branch instead of the commit, so the Edit/Delete buttons will be enabled on the "View file" page, if needed.](https://user-images.githubusercontent.com/1402241/69044026-c5b17d80-0a26-11ea-86ae-c95f89d3669a.png) ← https://github.com/sindresorhus/refined-github/pull/2529

- [](# "html-preview-link") [Adds a link to preview HTML files.](https://user-images.githubusercontent.com/44045911/67634792-48995980-f8fb-11e9-8b6a-7b57d5b12a2f.png) ← https://github.com/sindresorhus/refined-github/pull/2505

- [](# "conflict-marker") [Shows which PRs have conflicts in PR lists.](https://user-images.githubusercontent.com/9092510/62777551-2affe500-baae-11e9-8ba4-67f078347913.png) ← https://github.com/sindresorhus/refined-github/pull/2310

**Comment by fregante** [comment]
September 2019


- [](# "expand-all-collapsed-code") [Expands the entire file when you <kbd>alt</kbd> <kbd>click</kbd> on any "Expand code" button in diffs.](https://user-images.githubusercontent.com/44227187/64923605-d0138900-d7e3-11e9-9dc2-461aba81c1cb.gif) ← https://github.com/sindresorhus/refined-github/pull/2434

- [](# "embed-gist-via-iframe") [Adds a menu item to embed a gist via `<iframe>`.](https://user-images.githubusercontent.com/44045911/63633382-6a1b6200-c67a-11e9-9038-aedd62e4f6a8.png) ← https://github.com/sindresorhus/refined-github/pull/2347

- [](# "toggle-everything-with-alt") [Adds a shortcut to toggle all similar items (minimized comments, deferred diffs, etc) at once: <kbd>alt</kbd> <kbd>click</kbd> on each button or checkbox.](https://user-images.githubusercontent.com/37769974/62208543-dcb75b80-b3b4-11e9-984f-ddb479ea149d.gif) ← https://github.com/sindresorhus/refined-github/pull/2087


- [](# "deemphasize-unrelated-commit-references") [Makes it easier to tell apart commits added to the current PR versus plain commits that reference the PR.](https://user-images.githubusercontent.com/1402241/64478939-398b0a80-d1da-11e9-8c6a-bb98668cb78c.gif) ← https://github.com/sindresorhus/refined-github/pull/2415

- [](# "reload-failed-proxied-images") [Retries downloading images that failed downloading due to GitHub limited proxying.](https://user-images.githubusercontent.com/14858959/64068746-21991100-cc45-11e9-844e-827f5ac9b51e.png) ← https://github.com/sindresorhus/refined-github/pull/2393

**Comment by fregante** [comment]
October 2019

- [](# "link-to-prior-blame-line") [Preserves the current line on “View blame prior to this change” links.](https://user-images.githubusercontent.com/1402241/60064482-26b47e00-9733-11e9-803c-c113ea612fbe.png) ← https://github.com/sindresorhus/refined-github/pull/2481
- [](# "separate-draft-pr-button") [Lets you create draft pull requests in one click.](https://user-images.githubusercontent.com/202916/67269317-cd791300-f4b6-11e9-89d1-392de7ef71e1.png) ← https://github.com/sindresorhus/refined-github/pull/2486

**Comment by fregante** [comment]
November 2019

- [](# "user-local-time") [Shows the user local time in their hovercard (based on their last commit).](https://user-images.githubusercontent.com/1402241/69863648-ef449180-12cf-11ea-8f36-7c92fc487f31.gif) ← https://github.com/sindresorhus/refined-github/pull/2549
- [](# "repo-age") [Adds the age of the repository to the statistics bar.](https://user-images.githubusercontent.com/3848317/69494069-7d2b1180-0eb7-11ea-9aa1-d4194e566340.png) ← https://github.com/sindresorhus/refined-github/pull/2560
- [](# "linkify-user-location") [Linkifies the user location in their hovercard and profile page.](https://user-images.githubusercontent.com/1402241/69076885-00d3a100-0a67-11ea-952a-690acec0826f.png) ← https://github.com/sindresorhus/refined-github/pull/2544
- [](# "linkify-labels-on-dashboard") [Makes labels clickable in the dashboard’s "Recent activity" box.](https://user-images.githubusercontent.com/1402241/69045444-6ef97300-0a29-11ea-99a3-9a622c395709.png) ← https://github.com/sindresorhus/refined-github/pull/2513
- [](# "fix-view-file-link-in-pr") [Points the "View file" in PRs to the branch instead of the commit, so the Edit/Delete buttons will be enabled on the "View file" page, if needed.](https://user-images.githubusercontent.com/1402241/69044026-c5b17d80-0a26-11ea-86ae-c95f89d3669a.png) ← https://github.com/sindresorhus/refined-github/pull/2529
- [](# "html-preview-link") [Adds a link to preview HTML files.](https://user-images.githubusercontent.com/44045911/67634792-48995980-f8fb-11e9-8b6a-7b57d5b12a2f.png) ← https://github.com/sindresorhus/refined-github/pull/2505
- [](# "conflict-marker") [Shows which PRs have conflicts in PR lists.](https://user-images.githubusercontent.com/9092510/62777551-2affe500-baae-11e9-8ba4-67f078347913.png) ← https://github.com/sindresorhus/refined-github/pull/2310

**Comment by fregante** [comment]
December 2019 - January 2020

- Lots of small refinements of existing features
- [](# "quick-mention") [Adds a button to `@mention` a user in discussions.](https://user-images.githubusercontent.com/1402241/70406615-f445d580-1a73-11ea-9ab1-bf6bd9aa70a3.gif) ← https://github.com/sindresorhus/refined-github/pull/2556
- "Requested changes" in PRs now have a friendlier color. ← #2611

**Comment by fregante** [comment]
February 2020

 - [](# "expand-all-hidden-comments") [On long discussions where GitHub hides comments under a "Load more...", <kbd>alt</kbd> <kbd>click</kbd> will load *all* the comments at once instead of part of them.](https://user-images.githubusercontent.com/1402241/73838332-0c548e00-4846-11ea-935f-28d728b30ae9.png)  ← https://github.com/sindresorhus/refined-github/pull/2754
 - [](# "bugs-tab") [Adds a "Bugs" tab to repos, if there are any open issues with the "bug" label.](https://user-images.githubusercontent.com/1402241/73720910-a688d900-4755-11ea-9c8d-70e5ddb3bfe5.png)  ← https://github.com/sindresorhus/refined-github/pull/2750
 - [](# "extend-discussion-status-filters") [Lets you toggle between is:open/is:closed/is:merged filters in searches.](https://user-images.githubusercontent.com/1402241/73605061-2125ed00-45cc-11ea-8cbd-41a53ae00cd3.gif)  ← https://github.com/sindresorhus/refined-github/pull/2745
- `latest-tag-button` now tells you whether the default branch matches the latest published version.  ← #2771

**Comment by fregante** [comment]
April 2020

- [](# "clear-pr-merge-commit-message") [Clears the PR merge commit message of clutter, leaving only deduplicated co-authors.](https://user-images.githubusercontent.com/1402241/79257078-62b6fc00-7e89-11ea-8798-c06f33baa94b.png) (#3003)

- [](# "go-to-action-from-file") [Adds a link to access the past runs of a GitHub Action workflow when seeing the workflow configuration file.](https://user-images.githubusercontent.com/1402241/80146153-ab6d6400-85b1-11ea-9f38-e87950692a62.png) #3011)

- [](# "action-used-by-link") [Lets you see how others are using the current Action in the Marketplace.](https://user-images.githubusercontent.com/8360597/80250140-86d9c080-8673-11ea-9d28-f62faf9fd3d4.png) #3033)

- [](# "batch-mark-files-as-viewed") [Mark/unmark multiple files as “Viewed” in the PR Files tab. Click on the first checkbox you want to mark/unmark and then `shift`-click another one; all the files between the two checkboxes will be marked/unmarked as “Viewed”.](https://user-images.githubusercontent.com/1402241/79343285-854f2080-7f2e-11ea-8d4c-a9dc163be9be.gif) #3007)

- [](# "linkify-notification-repository-header") [Linkifies the header of each notification group (when grouped by repository).](https://user-images.githubusercontent.com/1402241/80849887-81531c00-8c19-11ea-8777-7294ce318630.png) #3048)

**Comment by fregante** [comment]
March 2020

- [Marks merge commits in commit lists.](https://user-images.githubusercontent.com/16872793/75561016-457eb900-5a14-11ea-95e1-a89e81ee7390.png) ← #2832 
- [Adds the updated time to pinned issues.](https://user-images.githubusercontent.com/1402241/75525936-bb524700-5a4b-11ea-9225-466bda58b7de.png) ← #2795
- [In your forked repos, shows number of your open PRs to the original repo.](https://user-images.githubusercontent.com/1922624/76398271-e0648500-637c-11ea-8210-53dda1be9d51.png) ← #2880
- [Clone a branch from the branches list.](https://user-images.githubusercontent.com/16872793/76802029-2a020500-67ad-11ea-95dc-bee1b1352976.png) ← #2896
- [When exploring blames, `Alt`-clicking the “Reblame” buttons will extract the associated PR’s commits first, instead of treating the commit a single change.](https://user-images.githubusercontent.com/16872793/77248541-8e3f2180-6c10-11ea-91d4-221ccc0ecebb.png) ← #2881

**Comment by fregante** [comment]
April 2020

- [](# "discussion-links-on-repo-lists") [Adds a link to the issues and pulls on the user profile repository tab and global search.](https://user-images.githubusercontent.com/16872793/78712349-82c54900-78e6-11ea-8328-3c2d39a78862.png) ← #2981
- [](# "clear-pr-merge-commit-message") [Clears the PR merge commit message of clutter, leaving only deduplicated co-authors.](https://user-images.githubusercontent.com/1402241/79257078-62b6fc00-7e89-11ea-8798-c06f33baa94b.png) ← #3003
- [](# "go-to-action-from-file") [Adds a link to access the past runs of a GitHub Action workflow when seeing the workflow configuration file.](https://user-images.githubusercontent.com/1402241/80146153-ab6d6400-85b1-11ea-9f38-e87950692a62.png) ← #3011
- [](# "action-used-by-link") [Lets you see how others are using the current Action in the Marketplace.](https://user-images.githubusercontent.com/8360597/80250140-86d9c080-8673-11ea-9d28-f62faf9fd3d4.png) ← #3033
- [](# "batch-mark-files-as-viewed") [Mark/unmark multiple files as “Viewed” in the PR Files tab. Click on the first checkbox you want to mark/unmark and then `shift`-click another one; all the files between the two checkboxes will be marked/unmarked as “Viewed”.](https://user-images.githubusercontent.com/1402241/79343285-854f2080-7f2e-11ea-8d4c-a9dc163be9be.gif) ← #3007

**Comment by fregante** [comment]
May 2020

- [](# "linkify-notification-repository-header") [Linkifies the header of each notification group (when grouped by repository).](https://user-images.githubusercontent.com/1402241/80849887-81531c00-8c19-11ea-8777-7294ce318630.png) ← #3048
- [](# "stop-redirecting-in-notification-bar") [Stops redirecting to notification inbox from notification bar actions while holding <kbd>Alt</kbd>.](https://user-images.githubusercontent.com/202916/80318782-c38cef80-880c-11ea-9226-72c585f42a51.png) ← #3036
- [](# "unwrap-useless-dropdowns") [Makes some dropdowns 1-click instead of unnecessarily 2-click.](https://user-images.githubusercontent.com/1402241/80859624-9bfdb300-8c62-11ea-837f-7b7a28e6fdfc.png) ← #3050
- [](# "clean-notifications") [Removes redundant user/repo from notifications when being grouped by repository](https://user-images.githubusercontent.com/37769974/80862883-0419bc80-8c96-11ea-84a7-15baf1eac0e6.png) ← #3051
- [](# "prevent-pr-commit-link-loss") [Suggests fixing your PR Commit links before commenting. GitHub has a bug that causes these link to appear as plain commit links, without association to the PR.](https://user-images.githubusercontent.com/1402241/82131169-93fd5180-97d2-11ea-9695-97051c55091f.gif) ← #3085
- [](# "show-associated-branch-prs-on-fork") [Shows the associated pull requests on branches for forked repository’s.](https://user-images.githubusercontent.com/16872793/81504659-7e5ec800-92b8-11ea-9ee6-924110e8cca1.png) ← #3116
- [Only show `comments-time-machine-links` after visiting the link](https://user-images.githubusercontent.com/1402241/82813824-24ecc080-9e96-11ea-8548-0927752f50b9.png) ← #3135

**Comment by fregante** [comment]
Each [release](https://github.com/sindresorhus/refined-github/releases) now includes a changelog 🎉 

Subscribe to releases at the [top of this page](#start-of-content) to get timely updates:

<img width="483" alt="" src="https://user-images.githubusercontent.com/1402241/92977621-14ffe900-f453-11ea-8ce5-ec09777fc375.png">
