### ISSUE TITLE
WIP: PR merge checklist

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2638]
## Events

Most of these are due to [GitHub losing events on AJAX navigation](https://github.com/sindresorhus/refined-github/issues/1247)

- [ ] Avoids JSX events like `onClick` (use `delegate-it` instead)
- [ ] Avoids `element.addEventListener` (use `delegate-it` instead)
- [ ] The first parameter of `delegate` is `document`/`document.body`, not anything inside the ajax container

## Meta
- [ ] `screenshot` is not `false` unless really hard to show
- [ ] `[](# feature-name)` in `readme` is the right one, not the name of another copy-pasted feature
