### ISSUE TITLE
Fix some TODOs in the code (also TypeScript-related)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2721]
https://github.com/sindresorhus/refined-github/blob/master/test/page-detect.ts
- [x] [1](https://github.com/sindresorhus/refined-github/blob/42fa0d72e3a2328cebf4044691949fd918dcfef4/test/page-detect.ts#1): TODO: resolve this exception. AVA doesn't run without reference

https://github.com/sindresorhus/refined-github/blob/master/test/utils.ts
- [ ] [1](https://github.com/sindresorhus/refined-github/blob/42fa0d72e3a2328cebf4044691949fd918dcfef4/test/utils.ts#1): TODO: resolve this exception. AVA doesn't run without reference

https://github.com/sindresorhus/refined-github/blob/master/source/features/quick-review-buttons.tsx
- [ ] [79](https://github.com/sindresorhus/refined-github/blob42fa0d72e3a2328cebf4044691949fd918dcfef4/source/features/quick-review-buttons.tsx#79): TODO: maybe `data-disable-with` can do this like it does for the generic "Comment" button

https://github.com/sindresorhus/refined-github/blob/master/source/features/revert-file.tsx
- [ ] [96](https://github.com/sindresorhus/refined-github/blob42fa0d72e3a2328cebf4044691949fd918dcfef4/source/features/revert-file.tsx#96): TODO: find this info on the page ("was this file created by this PR?")

https://github.com/sindresorhus/refined-github/blob/master/source/features/pr-filters.tsx
- [x] [67](https://github.com/sindresorhus/refined-github/blob42fa0d72e3a2328cebf4044691949fd918dcfef4/source/features/pr-filters.tsx#67): TODO: replace this with an API call
