### ISSUE TITLE
Highlight new Refined GitHub features in dashboard

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#818]
Continuing from #637 

Refined GitHub could use GitHub's dashboard broadcasts/notifications to highlight our own recent big changes and features (and implemented as a reusable package)

<img width="320" alt="RGH broadcast mockup" src="https://user-images.githubusercontent.com/1402241/28360936-96072408-6ca9-11e7-8264-f1b2bc88fa6e.png">

**Comment by hkdobrev** [comment]
I like how OctoLinker do a GitHub release full of info and emoji and then they open when the extension updates to a new minor version.

**Comment by bfred-it** [comment]
I like this implementation: https://github.com/vitalets/github-trending-repos

- [ ] Create `locked`+`closed` issue
- [ ] Manually add comments whenever some worthwhile feature is added
- [ ] Open page when users install it, prompting them to follow if they want. Old users will get a one-time tab as well.

**Comment by sindresorhus** [comment]
Sounds good :)

**Comment by bfred-it** [comment]
https://github.com/sindresorhus/refined-github/issues/1135

**Comment by bfred-it** [comment]
**However,** we probably need to just update the second comment or else the latest info will be at the bottom. Perhaps: 

1. Copy the previous comment's content
2. Create new comment with the updates
3. Append the previous comment's content
4. Delete the previous comment

This way we get the notifications **and** we keep the discussion to 2 comments.

**Comment by sindresorhus** [comment]
@bfred-it Or we can just reverse the comment order in RG ;)

**Comment by sindresorhus** [comment]
Or hide all comments except for the last one (newest).

**Comment by bfred-it** [comment]
Sure. Code vs manual work. 😃

 We can collapse the old ones but we should still delete them at that point otherwise the page will become too long.
